/// <reference types="next" />
/// <reference types="next/image-types/global" />

// ─── PDF.js 글로벌 타입 선언 ──────────────────────────────────

interface Window {
  pdfjsLib?: {
    GlobalWorkerOptions: {
      workerSrc: string;
    };
    getDocument(params: { data: ArrayBuffer } | { url: string }): {
      promise: Promise<PDFDocumentProxy>;
    };
  };
}

interface PDFDocumentProxy {
  numPages: number;
  getPage(pageNumber: number): Promise<PDFPageProxy>;
}

interface PDFPageProxy {
  getTextContent(): Promise<PDFTextContent>;
}

interface PDFTextContent {
  items: PDFTextItem[];
}

interface PDFTextItem {
  str: string;
  [key: string]: any;
}

// NOTE: This file is auto-generated by Next.js.
// You should not add any imports in this file.
// Read more at https://nextjs.org/docs/basic-features/typescript
